package com.DSALatency;

public enum Audit {
    NO_PARSER, PARSER_FOUND, PARSE_EXCEPTION, PARSE_SUCCESS, NO_PATH, PATH_FOUND, NO_TIME, TIME_FOUND, NO_TOPIC, TOPIC_FOUND, NO_RESPONSE_TIME, RESPONSE_TIME_FOUND, LOCATION_FOUND, DSA_STARTS_WITH, DSA_FOUND, INFER_STARTS_WITH, INFER_FOUND, NO_LOCATION
}
